apiVersion: apps/v1
kind: Deployment
metadata:
  name: wine-quality-inference
  labels:
    app: wine-quality
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wine-quality
  template:
    metadata:
      labels:
        app: wine-quality
    spec:
      containers:
        - name: inference-container
          image: wine-quality-inference:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"