apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-interface-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-interface
  template:
    metadata:
      labels:
        app: user-interface
    spec:
      containers:
      - name: user-interface
        image: rionewman/user-interface:latest
        ports:
        - containerPort: 5003
        volumeMounts:
        - name: user-volume
          mountPath: "/mnt/user"
        - name: data-volume
          mountPath: "/mnt/data"
      volumes:
      - name: user-volume
        persistentVolumeClaim:
          claimName: user-pvc
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      restartPolicy: Always

---
apiVersion: batch/v1
kind: Job
metadata:
  name: data-preprocessing-job
spec:
  template:
    spec:
      containers:
      - name: data-preprocessing
        image: rionewman/data-preprocessing:latest
        volumeMounts:
        - name: raw-data-volume
          mountPath: "/mnt/raw_data"
        - name: user-volume
          mountPath: "/mnt/user"
        - name: data-volume
          mountPath: "/mnt/data"
        command: ["python", "./preprocess.py"]
      volumes:
      - name: raw-data-volume
        persistentVolumeClaim:
          claimName: raw-data-pvc
      - name: user-volume
        persistentVolumeClaim:
          claimName: user-pvc
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      restartPolicy: Never
  backoffLimit: 4  # Retries up to 4 times if it fails

---


apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-job
spec:
  template:
    spec:
      containers:
      - name: model-training
        image: rionewman/model-training:latest
        volumeMounts:
        - name: data-volume
          mountPath: "/mnt/data"
        - name: models-volume
          mountPath: "/mnt/models"
        env:
        - name: TRAINING_FILE_PATH
          value: "/mnt/data/cleaned_wine_quality.csv"
        - name: SAVED_MODEL_DIR
          value: "/mnt/models/saved_model.pkl"
        command: ["python", "./train_model.py"]
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: models-volume
        persistentVolumeClaim:
          claimName: models-pvc
      restartPolicy: Never
  backoffLimit: 4

---

apiVersion: batch/v1
kind: Job
metadata:
  name: model-inference-job
spec:
  template:
    spec:
      containers:
      - name: model-inference
        image: rionewman/model-inference:latest
        volumeMounts:
        - name: data-volume
          mountPath: "/mnt/data"
        - name: models-volume
          mountPath: "/mnt/models"
        - name: user-volume
          mountPath: "/mnt/user"
        command: ["python", "./inference.py"]
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: models-volume
        persistentVolumeClaim:
          claimName: models-pvc
      - name: user-volume
        persistentVolumeClaim:
          claimName: user-pvc
      restartPolicy: Never
  backoffLimit: 4