apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-interface-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-interface
  template:
    metadata:
      labels:
        app: user-interface
    spec:
      containers:
      - name: user-interface
        image: pravallikadocker123/user-interface:latest
        ports:
        - containerPort: 5003
        volumeMounts:
        - name: user-volume
          mountPath: "/volumes/user"
        - name: data-volume
          mountPath: "/volumes/data"
      volumes:
      - name: user-volume
        persistentVolumeClaim:
          claimName: user-pvc
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-preprocessing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-preprocessing
  template:
    metadata:
      labels:
        app: data-preprocessing
    spec:
      containers:
      - name: data-preprocessing
        image: pravallikadocker123/data-preprocessing:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: raw-data-volume
          mountPath: "/volumes/raw_data"
        - name: user-volume
          mountPath: "/volumes/user"
        - name: data-volume
          mountPath: "/volumes/data"
        command: ["python", "./preprocess.py"]
      volumes:
      - name: raw-data-volume
        persistentVolumeClaim:
          claimName: raw-data-pvc
      - name: user-volume
        persistentVolumeClaim:
          claimName: user-pvc
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-training
  template:
    metadata:
      labels:
        app: model-training
    spec:
      containers:
      - name: model-training
        image: pravallikadocker123/model-training:latest
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: data-volume
          mountPath: "/volumes/data"
        - name: models-volume
          mountPath: "/volumes/models"
        env:
        - name: TRAINING_FILE_PATH  # ✅ Fixed filename to match preprocessing output
          value: "/volumes/data/cleaned_wine_quality.csv"
        - name: SAVED_MODEL_DIR
          value: "/volumes/models/saved_model.pkl"
        command: ["python", "./train_model.py"]
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: models-volume
        persistentVolumeClaim:
          claimName: models-pvc
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-inference-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-inference
  template:
    metadata:
      labels:
        app: model-inference
    spec:
      containers:
      - name: model-inference
        image: pravallikadocker123/model-inference:latest
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: data-volume
          mountPath: "/volumes/data"
        - name: models-volume
          mountPath: "/volumes/models"
        - name: user-volume
          mountPath: "/volumes/user"
        command: ["python", "./inference.py"]
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: models-volume
        persistentVolumeClaim:
          claimName: models-pvc
      - name: user-volume
        persistentVolumeClaim:
          claimName: user-pvc
      restartPolicy: Always