version: "3.9"

services:
  webapp:
    build: .
    container_name: webapp
    ports:
      - "5000:5000"
    volumes:
      - /mnt/userinputs:/mnt/userinputs
      - /mnt/data:/mnt/data
    depends_on:
      - preprocessing
      - inference
    networks:
      - app_network

  preprocessing:
    image: preprocessing-container  # Replace with your actual preprocessing image name
    container_name: preprocessing
    volumes:
      - /mnt/userinputs:/mnt/userinputs
      - /mnt/data:/mnt/data
    networks:
      - app_network

  inference:
    image: inference-container  # Replace with your actual inference image name
    container_name: inference
    volumes:
      - /mnt/data:/mnt/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
