version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Mount the app directory
    environment:
      - FLASK_APP=winequality_app.py
      - FLASK_RUN_HOST=0.0.0.0
      - MODEL_FILE_PATH=/app/my_wine_model.joblib  # Model file path
    command: flask run --host=0.0.0.0
