version: "3.9"

services:
  webapp:
    build: ./user-interface
    container_name: webapp
    ports:
      - "5003:5003"  # Only expose web app externally
    volumes:
      - user:/mnt/user
      - data:/mnt/data
    depends_on:
      - model-training  # Ensure the model is trained before accepting input
    networks:
      - app_network

  data-preprocessing:
    build: ./data-preprocessing
    container_name: data-preprocessing
    expose:
      - "5000"
    volumes:
      - raw_data:/mnt/raw_data  # 🔹 Ensures raw data is accessible
      - user:/mnt/user
      - data:/mnt/data
    networks:
      - app_network
    command: ["python", "/app/preprocess.py"]  # Runs preprocessing at startup

  model-training:
    build: ./model-training
    container_name: model-training
    expose:
      - "5001"
    volumes:
      - data:/mnt/data
      - models:/mnt/models
    networks:
      - app_network
    depends_on:
      - data-preprocessing  # 🔹 Ensure preprocessing is completed before training starts
    command: ["python", "/app/train_model.py"]

  model-inference:
    build: ./model-inference
    container_name: model-inference
    expose:
      - "5002"
    volumes:
      - data:/mnt/data
      - models:/mnt/models
    networks:
      - app_network
    depends_on:
      - model-training  # 🔹 Ensure trained model exists before inference

volumes:
  user:  # 🔹 User input for predictions
  data:  # 🔹 Processed data storage
  models:  # 🔹 Trained models
  raw_data: /raw_data

networks:
  app_network:
    driver: bridge
