apiVersion: v1
kind: Secret
metadata:
  name: github-token
type: Opaque
data:
  GITHUB_TOKEN: Z2l0aHViX3BhdF8xMUJBWEhDNVEwUjl5em9NZ3RRbGJ2X2dxcWR5YVIwdWRXZTY1N3pKcWhCTjRNc3lqTEFDR0d6SXkwMVpwN0FsUHoySURaRERYTEJlbTI5TjBF
---
