apiVersion: v1
kind: Service
metadata:
  name: data-preprocessing-service
spec:
  selector:
    app: data-preprocessing
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
  type: ClusterIP