apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-preprocessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-preprocessing
  template:
    metadata:
      labels:
        app: data-preprocessing
    spec:
      containers:
      - name: data-preprocessing
        image: pariikubavat/data-preprocessing:latest
        ports:
        - containerPort: 5004
        volumeMounts:
        - name: wine-storage
          mountPath: /app/volumes/data  # Saving cleaned_wine_quality.csv & wine_quality.json here
        - name: wine-storage
          mountPath: /app/volumes/user  # Saving cleaned_input.csv here after processing
      volumes:
      - name: wine-storage
        persistentVolumeClaim:
          claimName: wine-pvc