apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-inference
  labels:
    app: model-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-inference
  template:
    metadata:
      labels:
        app: model-inference
    spec:
      containers:
        - name: model-inference
          image: pariikubavat/model-inference:latest
          ports:
            - containerPort: 5001
          volumeMounts:
            - mountPath: /app/volumes/models
              name: models-volume
            - mountPath: /app/volumes/user
              name: user-volume
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: models-volume
          persistentVolumeClaim:
            claimName: models-volume-pvc
        - name: user-volume
          persistentVolumeClaim:
            claimName: user-volume-pvc