apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-training
  template:
    metadata:
      labels:
        app: model-training
    spec:
      containers:
      - name: model-training
        image: pariikubavat/model-training:latest
        volumeMounts:
        - mountPath: /app/volumes/models
          name: models-volume
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: models-volume-pvc