apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-inference
  template:
    metadata:
      labels:
        app: model-inference
    spec:
      containers:
        - name: model-inference
          image: pariikubavat/model-inference:latest
          ports:
            - containerPort: 5001
          volumeMounts:
            - name: models-volume
              mountPath: /app/volumes/models
            - name: user-volume
              mountPath: /app/volumes/user
      volumes:
        - name: models-volume
          persistentVolumeClaim:
            claimName: models-volume-pvc
        - name: user-volume
          persistentVolumeClaim:
            claimName: user-volume-pvc