apiVersion: v1
kind: PersistentVolume
metadata:
  name: wine-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Users/pariikubavat/wine-quality 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wine-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi