apiVersion: v1
kind: Service
metadata:
  name: data-preprocessing-service
spec:
  selector:
    app: data-preprocessing
  type: NodePort
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
      nodePort: 30004