apiVersion: v1
kind: Service
metadata:
  name: model-inference-service
spec:
  selector:
    app: model-inference
  type: NodePort
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001