apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-interface
  labels:
    app: user-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-interface
  template:
    metadata:
      labels:
        app: user-interface
    spec:
      containers:
        - name: user-interface
          image: pariikubavat/user-interface:latest
          ports:
            - containerPort: 5003
          volumeMounts:
            - mountPath: /app/volumes/user
              name: user-volume
            - mountPath: /app/volumes/models
              name: models-volume
            - mountPath: /app/volumes/data
              name: data-volume
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: user-volume
          persistentVolumeClaim:
            claimName: user-volume-pvc
        - name: models-volume
          persistentVolumeClaim:
            claimName: models-volume-pvc
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume-pvc