apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-interface
  template:
    metadata:
      labels:
        app: user-interface
    spec:
      containers:
      - name: user-interface
        image: pariikubavat/user-interface:latest  
        ports:
        - containerPort: 5003
        env:
        - name: USER_DIR
          value: "/app/volumes/user"
        - name: INFERENCE_API
          value: "http://model-inference-service:5001/predict"
        volumeMounts:
        - name: user-volume
          mountPath: "/app/volumes/user"
      volumes:
      - name: user-volume
        persistentVolumeClaim:
          claimName: user-volume-pvc