apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-interface
  template:
    metadata:
      labels:
        app: user-interface
    spec:
      containers:
        - name: user-interface
          image: pariikubavat/user-interface:latest
          ports:
            - containerPort: 5003
          volumeMounts:
            - name: data-volume
              mountPath: /app/volumes/data
            - name: models-volume
              mountPath: /app/volumes/models
            - name: user-volume
              mountPath: /app/volumes/user
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume-pvc
        - name: models-volume
          persistentVolumeClaim:
            claimName: models-volume-pvc
        - name: user-volume
          persistentVolumeClaim:
            claimName: user-volume-pvc