version: "3.7"

services:
  model-training:
    image: pravallikadocker123/model-training:v3
    deploy:
      replicas: 2
    ports:
      - "5001:5001"  # Map the container port to the host
    secrets:
      - GITHUB_TOKEN
    environment:
      ROLLBACK_ENABLED: "true"
      TRAINING_FILE_PATH: "/app/data/wine_quality_assignment.csv"
      LOG_LEVEL: "DEBUG"
    volumes:
      - ./data:/app/data  # Mount local data directory for persistence

secrets:
  GITHUB_TOKEN:
    external: true
