apiVersion: v1
kind: Secret
metadata:
  name: github-token
type: Opaque
data:
  GITHUB_TOKEN: Z2l0aHViX3BhdF8xMUJBWEhDNVEwUjl5em9NZ3RRbGJ2X2dxcWR5YVIwdWRXZTY1N3pKcWhCTjRNc3lqTEFDR0d6SXkwMVpwN0FsUHoySURaRERYTEJlbTI5TjBF
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
type: Opaque
data:
  DOCKER_USERNAME: cHl0aG9ucHJhdg==
  DOCKER_PASSWORD: R2l0aHViMzAj # Replace with the Base64-encoded password
