apiVersion: v1
kind: ConfigMap
metadata:
  name: model-training-config
  namespace: default
data:
  TRAINING_FILE_PATH: "/app/Data/wine_quality_assignment.csv"
  SAVED_MODEL_PATH: "/app/saved_model"
  LOG_LEVEL: "DEBUG"
  RANDOM_FOREST_N_ESTIMATORS: "100"  # Number of trees in the forest
  RANDOM_FOREST_MAX_DEPTH: "20"  # Maximum depth of each tree
  RANDOM_FOREST_MIN_SAMPLES_SPLIT: "2"  # Minimum samples required to split an internal node
  RANDOM_FOREST_MIN_SAMPLES_LEAF: "1"  # Minimum samples required to be at a leaf node
  RANDOM_FOREST_MAX_FEATURES: "sqrt"  # Number of features to consider for the best split
