apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training
  labels:
    app: model-training
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model-training
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: model-training
    spec:
      containers:
      - name: model-training
        image: model-training:latest
        ports:
          - containerPort: 5000
        volumeMounts:
          - name: data-volume
            mountPath: /app/volumes/data
          - name: model-volume
            mountPath: /app/volumes/models
          - name: user-volume
            mountPath: /app/volumes/user
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: dataset-pvc
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-pvc
      - name: user-volume
        persistentVolumeClaim:
          claimName: userinput-pvc