apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training
  labels:
    app: model-training
spec:
  replicas: 2  # High availability
  selector:
    matchLabels:
      app: model-training
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: model-training
    spec:
      containers:
      - name: model-training
        image: pravallikadocker123/model-training:latest
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: data-volume
          mountPath: /app/Data  # Mount the data directory into the container
        env:
        - name: ROLLBACK_ENABLED
          value: "true"  # Enable rollback for safer deployments
        - name: TRAINING_FILE_PATH
          value: "/app/Data/wine_quality_assignment.csv"  # Path to the training data
        - name: LOG_LEVEL
          value: "DEBUG"  # Set log verbosity
        envFrom:
        - configMapRef:
            name: model-training-config  # Includes TRAINING_FILE_PATH, LOG_LEVEL, etc.
        - secretRef:
            name: github-token            
        - secretRef:
            name: docker-credentials  # Includes DOCKER_USERNAME, DOCKER_PASSWORD
        readinessProbe:
          httpGet:
            path: /train
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 20
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        volumeMounts:
        - name: data-volume
          mountPath: /app/Data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc  # Dynamic volume provisioning



