kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataset-pvc  
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/AISDP-Project/data
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: model-pvc  
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: model-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/AISDP-Project/model
  persistentVolumeReclaimPolicy: Retain

# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: data-pv
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: /mnt/AISDP-Project/Data
#   persistentVolumeReclaimPolicy: Retain
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: data-pvc
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 5Gi
