apiVersion: v1
kind: Service
metadata:
  name: data-preprocessing-service
  labels:
    app: data-preprocessing
spec:
  selector:
    app: data-preprocessing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  # ClusterIP if no external access needed