apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-preprocessing
  labels:
    app: data-preprocessing
spec:
  replicas: 3  # Deploy 3 pods for redundancy
  selector:
    matchLabels:
      app: data-preprocessing
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: data-preprocessing
    spec:
      containers:
      - name: data-preprocessing
        image: pengpengintotheroom/preprocess:latest  # Replace if needed
        ports:
          - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: FLASK_ENV
            value: "production"
        volumeMounts:
          - name: data-volume
            mountPath: "/volumes/data"
          - name: user-volume
            mountPath: "/volumes/user"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        imagePullPolicy: Always
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: user-volume
        persistentVolumeClaim:
          claimName: user-pvc
      restartPolicy: Always