apiVersion: v1
kind: Service
metadata:
  name: data-preprocessing-service
spec:
  selector:
    app: data-preprocessing
  ports:
    - protocol: TCP
      port: 80  # External access port
      targetPort: 5000  # Flask's internal port
  type: LoadBalancer