apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-preprocessing
  labels:
    app: data-preprocessing
spec:
  replicas: 3  # Ensures high availability (scaling)
  selector:
    matchLabels:
      app: data-preprocessing
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: data-preprocessing
    spec:
      containers:
        - name: data-preprocessing
          image: pengpengintotheroom/preprocess:latest  # Update with actual Docker image
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: FLASK_ENV
              value: "production"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
      restartPolicy: Always
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
        - name: user-volume
          persistentVolumeClaim:
            claimName: user-pvc